<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-parent</artifactId>
        <version>11.8.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>flyway-database-dm</artifactId>
    <version>${parent.version}.apexsoft</version>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <dm.version>8.1.3.140</dm.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>flyway-core</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.dameng/DmJdbcDriver16 -->
        <dependency>
            <groupId>com.dameng</groupId>
            <artifactId>DmJdbcDriver16</artifactId>
            <version>${dm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>